### ISSUE TITLE
connecting to S3

### ISSUE THREAD

**Issue by soumya-github** [Daniel-t/node-red-contrib-aws#11]
I am trying to connect to AWS S3 using the S3 node. I am giving my accesskey ans secret key as required but after deploying my console is showing error "Flows stopped due to missing node types. Check logs for details." Please help. Console log  shoes " Waiting for missing types to be registered:" I tried to uncomment the console.log in  Please help.

**Comment by leonardobaiao** [comment]
I tried to simulate your problem, but it worked. Aws recommends the use of Role in EC2.

**Comment by soumya-github** [comment]
The problem is solved. You can close it.

regards,
Soumya
mobility:9903639236
