### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by felipeplets** [Daniel-t/node-red-contrib-aws#14]
Hello @Daniel-t, 

I'm CEO from Menvia and we are working on some Node Red modules here. 
One of them was a Node-RED AWS connection and we thought we can contribute a lot to the project to gain visibility and get other collaborators.

What do you think about joining efforts? 

All the best, 
Felipe

**Comment by Daniel-t** [comment]
Hi Felipe,

I'm happy to accept pull requests that maintain the structure of the existing code base.  Anything else and we can discuss separately.
