### ISSUE TITLE
msg.messageStructure appears to be ignored

### ISSUE THREAD

**Issue by seanboc** [Daniel-t/node-red-contrib-aws#15]
Hi,

I set the input msg object to have a json payload but I consistently get the error that "failed: InvalidParameterType: Expected params.Message to be a string"

**** The debug dump of the generated MSG object is given below:

msg : Object
object
_msgid: "2bf61ec7.a80782"
topic: ""
payload: object
default: "This is the default Message"
APNS_SANDBOX: "{ "aps" : { "alert" : "You have got email.", "badge" : 9,"sound" :"default"}}"
messageStructure: "json"

*** My function jS code is:

msg.messageStructure="json";
msg.payload={"default":"This is the default Message","APNS_SANDBOX":"{ \"aps\" : { \"alert\" : \"You have got email.\", \"badge\" : 9,\"sound\" :\"default\"}}"};

Does this actually work?

Thanks

Sean

**Comment by Daniel-t** [comment]
According to http://docs.aws.amazon.com/sns/latest/api/API_Publish.html the SNS Message (msg.payload) must be a string.  the MessageStructure attribute tells the AWS backend to parse it as JSON or not.  

In your example, you are posting an Object, changing it to msg.payload=JSON.stringify({"default":"This is the default Message","APNS_SANDBOX":"{ "aps" : { "alert" : "You have got email.", "badge" : 9,"sound" :"default"}}"}); should do the trick.

I did consider detecting if payload was an object and doing this automatically, but am cautious about moving away from being a straight 'wrapper' in this case.

**Comment by seanboc** [comment]
Yup that did it. Thank you. Appreciate your help and contribution to the
open source community.

Regards

Sean
