### ISSUE TITLE
Acknowledges on DynamoDB

### ISSUE THREAD

**Issue by fcabrera23** [Daniel-t/node-red-contrib-aws#16]
Hi, i have two flows for saving on differents DBs. One flow messages are store on a Couch DB  and the other one uses this node to store messages on DynamoDB. The problem is that some messages are not being saved on DynamoDB, so i think the problem is on the node itself. Is there any way to get ACK when a PUT is exectued? Thanks

**Comment by Daniel-t** [comment]
if the putItem call is successful the node outputs a message with the payload equal to the data object in the callback (see http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#putItem-property).  This may be useful. 

Alternatively if there's an error, the node (all nodes in this set) currently output nothing, however the node should gain a red circle and and error reported in the logs with the issue.  Changing this behavior by default would be 'breaking' for many users so would need to be done carefully.

Let me know if either of these help or not.

**Comment by fcabrera23** [comment]
I've debugging and the response for successful package is { empty }. I will try to get the error message for making a flow to re save it
