### ISSUE TITLE
[Feature Request] EC2 list instances

### ISSUE THREAD

**Issue by nekloth** [Daniel-t/node-red-contrib-aws#18]
In the company I'm working, we handle hundreds of EC2 instances, all created usiong the same AWS account but internally charged back thanks to tags.

An interesting node is to list and filter EC2 instances.

Thanks to that, I should be able to monitor the EC2 charged to me and act in consequence

**Comment by Daniel-t** [comment]
This should be possible with the Describe Instance node:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#describeInstances-property

Submitting with a blank InstanceID should return a list of all instances.  I'll need to test this when I get a chance (or let me know if it does doesn't work).

Any filtering will need to be down outside the node as the intent of the library is to mirror the AWS API and not introduce functionality.

**Comment by nekloth** [comment]
I tried with an empty instanceID and got the error "No InstanceID specified":
![image](https://user-images.githubusercontent.com/4066135/28608669-86a36084-71e1-11e7-9975-153af917dfe8.png)

**Comment by Daniel-t** [comment]
Git version updated to enable a blank InstanceID for EC2/Describe

PLease let me know if it works for you

**Comment by nekloth** [comment]
Tested with an empty InstanceID and it works as exepected !

I got the full response JSON starting at "Reservation" level.

I agree on the filtering capabilities, it is great to keep it later in the flow.
