### ISSUE TITLE
[Feature request] ElasticSearch nodes

### ISSUE THREAD

**Issue by nekloth** [Daniel-t/node-red-contrib-aws#19]
Having AWS ES domains list and domain detail is a feature I'm really interesting in.

This can be don thanks to AWS CLI, having a node would be more than helpful.

**Comment by Daniel-t** [comment]
Looks ok,  references:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ES.html#describeElasticsearchDomain-property

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ES.html#listDomainNames-property
