### ISSUE TITLE
[Feature request] RDS nodes

### ISSUE THREAD

**Issue by nekloth** [Daniel-t/node-red-contrib-aws#20]
Similar to EC2, cousl be great to have RDS nodes to :
- describes instances
- create snapshots
- describe parameters group
- etc...

**Comment by Daniel-t** [comment]
Shouldn't be too hard, I haven't used RDS personally so not sure what functions would be useful.  Can you provide a list (assuming there are more than those listed above).

API Reference: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS.html

**Comment by nekloth** [comment]
I'm not a specialist or intensive user of RDS, but (according to me and my today's needs, to be honnest), I think following functions are interesting:

**for Instances**
- describeDBInstances
- describeDBParameterGroups
- describeDBParameters
- describeDBSecurityGroups


**for Administration**
- applyPendingMaintenanceAction
- modifyDBInstance
- rebootDBInstance
- startDBInstance
- stopDBInstance

**for Tags**
- listTagsForResource
- addTagsToResource
- removeTagsFromResource

**... and others**
- describeDBEngineVersions


Thanks

**Comment by Daniel-t** [comment]
AWS have released a specific API for managing Tags,  defering any tag management to a seperate node for tags.

**Comment by Daniel-t** [comment]
Added in  9ae6b8b.  But entirely untested as I dont have a use case.  Please test and let me know how it goes.

**Comment by Daniel-t** [comment]
Requires Testing

**Comment by nekloth** [comment]
I planned to lead some tests, but as soon as I will be back behind a computer (not before 2 weeks, sorry)

**Comment by nekloth** [comment]
First tests results (sorry for the delay):

## DescribeInstance
* Empty instance name is not accepted (```No Name Specified```). In that case, it could be interesting to get the full instance list.
* When entering an instance name (that exists in the selected region), got an error ```ReferenceError: iParams is not defined```

## Describe DB Engine Versions
* Empty name is not accepted (```No Name Specified```).
* When entering an instance name (that exists in the selected region), got an error ```ReferenceError: iParams is not defined```

## Describe Parameter group
* Empty name is not accepted (```No Name Specified```).
* When entering an instance name (that exists in the selected region), got an error ```ReferenceError: iParams is not defined```



... and I stopped my tested because I may miss use something (it is strange to always have the same iParams error...

**Comment by Daniel-t** [comment]
Closing due to no feedback
