### ISSUE TITLE
name conflict with node-red-node-aws

### ISSUE THREAD

**Issue by mblackstock** [Daniel-t/node-red-contrib-aws#22]
Some of the nodes - 'aws-config' and 'amazon s3' use the same name as the nodes in the node-red-node-aws nodes so they cannot be installed together.

**Comment by mblackstock** [comment]
I suggest we change the node types to begin with 'aws' instead of 'amazon' to avoid conflicts with the existing amazon s3 node.

**Comment by Daniel-t** [comment]
Fixed in a2bc4e8
