### ISSUE TITLE
Add Subject parameter to SNS publish

### ISSUE THREAD

**Issue by philipspigelmire** [Daniel-t/node-red-contrib-aws#30]
Would it be possible to add a subject parameter to the SNS publish node?

**Comment by Daniel-t** [comment]
@philipspigelmire please give this a go, and let me know if it works for you.

**Comment by philipspigelmire** [comment]
Thank you.

On first try I received: ReferenceError: inArg is not defined
Line 42 needs changed from inArg to arg

After that change, it works great. However, I think it would be better to provide both arguments so "Subject" can be all lower case in Node Red for consistency with everything else in Node Red.

Line 70: copyArg(msg,"subject",params,"Subject");

**Comment by Daniel-t** [comment]
I fixed line 42 in another commit (you must have gotten pretty unlucky to grab the broken one).

Thanks for testing I'll close this and create a new issue regarding case sensitivity (however I'm not keen on it,).
