### ISSUE TITLE
cannot set prefix when using s3 list object

### ISSUE THREAD

**Issue by hkanamaru** [Daniel-t/node-red-contrib-aws#32]
i cannot set prefix to get list of objects from s3 bucket.

**Comment by Daniel-t** [comment]
A major change was just commited, could you try again please.

**Comment by Echooff3** [comment]
Were you using an inject node to pass the JSON along? I was having a similar issue. That node passes the JSON as msg.payload.prefix. I threw a function after the inject to change the object to msg.Prefix. Which worked.

**Comment by Daniel-t** [comment]
Thanks @Echooff3, closing.
