### ISSUE TITLE
Looking for doc to configure S3 node

### ISSUE THREAD

**Issue by ThibautRuy** [Daniel-t/node-red-contrib-aws#38]
Hi @Daniel-t 

Your node-red contrib seems promissing, but I struggle a bit to use it. Where can I find how to configure the S3 node. I need to upload a base 64 coverted string to buffer in a PNG image to S3, so my question is where do I setup parameters: 

- filename
- ACL 
- Content type  

I do not find these in the node itself... neither I do not know how I pass my buffer file to the node (payload)...

Regards
Thibaut

**Comment by Daniel-t** [comment]
I'll add an example.

**Comment by Daniel-t** [comment]
As a general rule, the nodes are direct wrappers for the AWS Javascript API.  So details for the parameters for PutObject can be found here https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property

for your specific query, your message should have at least the following:
msg.Bucket - the bucket to store the file in (can be specified in the node config
msg.Key - the filename to save the file in S3 as (also in node config)
msg.Body - the content you want to save
msg.ACL - the acl you want applied (see the api docs)
msg.ContentType - the mime type
