### ISSUE TITLE
Docs required on "InstanceIds" field syntax under EC2 start instances

### ISSUE THREAD

**Issue by renjitrk** [Daniel-t/node-red-contrib-aws#39]
Hi,
Getting "failed: InvalidParameterType: Expected params.InstanceIds to be an Array" error while using StartInstance Operation under AWS EC2. Tried all possible sytaxs, but could not get anything working.
Examples tried: ['i-abcd1234'] ; {"InstanceIds":["i-abcd1234"],"DryRun":false,"Force":true} ; {"InstanceIds":["i-abcd1234"]} ; "InstanceIds":["i-abcd1234"]
Please help with the solution.
Thanks,
Renjith.

**Comment by Daniel-t** [comment]
Needs to be looked at. Ref https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#startInstances-property

**Comment by renjitrk** [comment]
Also, please note, on manually editing the 'InstanceIDs' field in node-red config file, the StartInstance node seems to work. Seems like some mapping issue. edited to something like this and it worked - ""payload": "[i-abcd1234]","
