### ISSUE TITLE
Firehose support 

### ISSUE THREAD

**Issue by myco** [Daniel-t/node-red-contrib-aws#41]
Hi, do you have Kinesis Firehose support in your plans?

**Comment by Daniel-t** [comment]
Not yet, but its easy to add new nodes now.   I'll add it to the list for a soonish release.

If your keen, you can build it by running gen_scripts/run_build.js , copy the firehose html and js scripts to the parent directory and updating the package.json.   If it works for you please issue a pull request and I'll bring it straight in.

**Comment by myco** [comment]
#42

**Comment by Daniel-t** [comment]
Added initial Firehose support, could you please test it and confirm if its functional.

This does not use msg.Payload as Record.

**Comment by myco** [comment]
So where is it? I can not find any correlated commit.

I think it's important to pass somehow records from other  blocks. It doesn't need to be msg.Payload. Can be msg.Record instead.

BTW. According to documentation https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Firehose.html#putRecord-property
 putRecord takes 'Record' as { Data: new Buffer(...) }

**Comment by Daniel-t** [comment]
Ok no idea what happened there. I’ll push another version today. 

You will be able to use Record to pass details in for those functions that support it.

**Comment by myco** [comment]
OK, it works! 
{ Data: new Buffer(data) }

Thank you
