### ISSUE TITLE
Add DynamoDB Converter Node (was AWS DynamoDB putitem params error)

### ISSUE THREAD

**Issue by Hugobox** [Daniel-t/node-red-contrib-aws#43]
Hi!
I'm trying to add an item to my DynamoDB table.
While it works if I input the item directly in the node's item field, I can't figure out how to do it dynamically via its msg input. I tried many things but every try so far yeilds this error: failed: InvalidParameterType: Expected params.Item to be a map

Could you put an example flow in the examples as I couldn't make it work with the example provided.
Thanks!

**Comment by MarcoBenini** [comment]
For example using a "function" node to prepare data for putItem in a DynamoDB table.
Primary key: partition "dev_id" and sort time (ISO 8601 format).

```
let ISOdatetime = new Date(msg.payload).toISOString();

msg.Item = {
    "dev_id": {
        "S": "test_001"
    },
    "time": {
        "S": ISOdatetime
    }
}

return msg;
```

Description of "Item" can be found in AWS Javascript SDK documentation -> putItem -> Parameters
[https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#putItem-property](url)

**Comment by Daniel-t** [comment]
Thanks @MarcoBenini 

@Hugobox did this answer your question?

**Comment by ThibautRuy** [comment]
Hi, 
This is a great node, it works for me as explain above, now, I would like to "detect" or automatically convert from javascript types a bit like in https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/Converter.html 

My difficulty is that I have a JSON object that I need to store containing around 50 different attributes, and I wonder if I could avoid to type each of the attribute type "S", "N", NULL, etc... but detect them automatically...

Does this make sense ? Is there a way to do this?

Thibaut

**Comment by Daniel-t** [comment]
I hadn't noticed the Converter object previously.   It will need a special node, happy to look into this

**Comment by Daniel-t** [comment]
I've added a node the the repository (not published yet), please try it out.  Cursory testing seems to be work as expected
