### ISSUE TITLE
AWS Kinesis Get Record Issue

### ISSUE THREAD

**Issue by drackyalcin** [Daniel-t/node-red-contrib-aws#44]
I cant get record using kinesis nodes. I am trying get shard iterator befonre get recoder there is an error.  How can i downgrade aws nodes ? Using ibm node red console

**Comment by Daniel-t** [comment]
Sorry, I cant help without more information.  I haven't used Kinesis much myself.
Can you post your flow and error message.

**Comment by Daniel-t** [comment]
Closing due to insufficient detail
