### ISSUE TITLE
Document Example for Rekcognition (was node-red (mips LEDE))

### ISSUE THREAD

**Issue by tcpipchip** [Daniel-t/node-red-contrib-aws#45]
Sir, good morning

I compiled the NODE-LED to MT7688 processor and it´s running well :)

I have a question about AWS REKOGNITON **"DetectText"** node, how i make the NODE-RED execute it ?

I already set it up (credentials and file) to work.

![image](https://user-images.githubusercontent.com/11488460/38363927-e07b81da-38ac-11e8-9879-92756481cff7.png)

![image](https://user-images.githubusercontent.com/11488460/38364076-7948bd42-38ad-11e8-9902-2145d1068fe4.png)

**Comment by Daniel-t** [comment]
I haven't used it myself, however referring to the API docs is a help
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Rekognition.html#detectText-property

your Message needs to have an Image object with either:
* Bytes: a base64 encoded buffer of your image
* S3Object: An object representing an S3 file (Bucket and Name attributes)

**Comment by tcpipchip** [comment]
Can you test there and report to us ?

**Comment by Daniel-t** [comment]
I've posted a wiki page with a working example which you should be able to rework to your needs
https://github.com/Daniel-t/node-red-contrib-aws/wiki/Rekognition
