### ISSUE TITLE
IotData node: Endpoint field is missing

### ISSUE THREAD

**Issue by giddyhup** [Daniel-t/node-red-contrib-aws#46]
Using the UpdateThingShadow operation the field to enter Endpoint information is not showing up. I installed node-red-contrib-aws through the palette manager in Node RED 0.18.4 (dockerized).

**Comment by Daniel-t** [comment]
Confirmed, looks like I forgot the IoTData patches.  New version to be published soon.

**Comment by Daniel-t** [comment]
new version published to npmjs as well, so you should be able to update from the pallete now.
