### ISSUE TITLE
Any plan to add AWS Redshift?

### ISSUE THREAD

**Issue by ThibautRuy** [Daniel-t/node-red-contrib-aws#49]
https://docs.aws.amazon.com/redshift/latest/APIReference/Welcome.html

**Comment by Daniel-t** [comment]
Adding Redshift should be easy enough, the API looks standard.
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Redshift.html

See the readme on how to build it yourself and I'll take a pull request, otherwise it will need till I get a chance to do it myself.
