### ISSUE TITLE
Great Work! How can I help?

### ISSUE THREAD

**Issue by tuskensp** [Daniel-t/node-red-contrib-aws#53]
I am successfully using the AWS DynamoDB node to scan a table and it is working great. One question I have is how difficult would it be to add a FilterExpression so that only part of the DynamoDB table is returned?

**Comment by Daniel-t** [comment]
It should be just a matter of adding the filterExpression to the payload before passing it in to the DynamoDB node.   I haven't tried it personally, however nodes should be feature complete.
