### ISSUE TITLE
aws sdk version stuck on 2.4

### ISSUE THREAD

**Issue by jomel** [Daniel-t/node-red-contrib-aws#55]
When I install this package through node-red the installed version of aws-sdk is 2.4.0
The latest version is 2.384!

I need to run at least version 2.7, which supports .fifo sqs queues.

You could change your package.json to be:
`  "dependencies": {  "aws-sdk": "^2"  }`
or
`  "dependencies": {  "aws-sdk": "2.x.x"  }`

**Comment by Daniel-t** [comment]
Just updated to AWS-SDK 2.829
