### ISSUE TITLE
/usr/src/node-red/node_modules/node-red-contrib-aws/Ecs.html does not exist

### ISSUE THREAD

**Issue by Pell17** [Daniel-t/node-red-contrib-aws#73]
I'm a Node-Red beginner, so bear with me...

Installed node-red-contrib-aws through "npm install" on Node-Red version 1.2.9 (official image from Docker Hub). Install itself was successful. When Node-Red starts it outputs the following:

`18 Mar 16:32:16 - [warn] [node-red-contrib-aws/AWS ECS] Error: /usr/src/node-red/node_modules/node-red-contrib-aws/Ecs.html does not exist`

Looking at `package.json` it says:

      "AWS ECS": "Ecs.js",

But the file is actually named `ECS.js`. When I change that line to:

      "AWS ECS": "ECS.js",

then Node-Red is happy.

**Comment by Daniel-t** [comment]
I can replicated the filename discrepancy, but not the error.

For some reason installing from NPM creates the files as ECS.js/html while using Git keeps them as Ecs.js/html.  I'm about to publish a minor update. please let me know if it resolves the issue (along with the version number you are using).

**Comment by Daniel-t** [comment]
SHould be resolved now
