### ISSUE TITLE
Nodes dont appear after install

### ISSUE THREAD

**Issue by ckglobalroaming** [Daniel-t/node-red-contrib-aws#9]
node-red-contrib-aws@0.1.3 node_modules/node-red-contrib-aws
├── minimatch@2.0.4 (brace-expansion@1.1.6)
└── aws-sdk@2.7.21 (sax@1.1.5, xml2js@0.4.15, uuid@3.0.0, querystring@0.2.0, url@0.10.3, jmespath@0.15.0, buffer@4.9.1, crypto-browserify@1.0.9, xmlbuilder@2.6.2)

No Nodes? any assistance please?

**Comment by Daniel-t** [comment]
I will have a look. Can you restart node red and post the logs (up until it starts the flow). 

Also which node red & nodejs versions are you using?

**Comment by Daniel-t** [comment]
Closing, cant replicate and no more info to identify issue
