### ISSUE TITLE
SQS: How to set request parameters for ReadMessage?

### ISSUE THREAD

**Issue by prathamesh-gharat** [Daniel-t/node-red-contrib-aws#90]
For example, how can we set MaxNumberOfMessages on the ReceiveMessage request?

Reference: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html

**Comment by prathamesh-gharat** [comment]
`MaxNumberOfMessages` property on the `msg` object 🚀 

Reference from code: `copyArg(msg,"MaxNumberOfMessages",params,undefined,false);`
Source: https://github.com/Daniel-t/node-red-contrib-aws/blob/master/SQS.js#L299

**Comment by Landsailor** [comment]
@prathamesh-gharat Does this work consistently for you?

I have _never_ received ten messages. The number is always between 1 and 5. Perhaps the speed of the AWS instance running Node-RED is the issue?
